# Etapa 1: Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Copiar csproj y restaurar dependencias
COPY perla_metro_stations_service_api.csproj ./
RUN dotnet restore perla_metro_stations_service_api.csproj

# Copiar todo el código y compilar
COPY . .
RUN dotnet publish -c Release -o /app/publish

# Etapa 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app

# Copiar la app publicada desde la etapa anterior
COPY --from=build /app/publish .

# Render asigna el puerto en la variable $PORT
ENV ASPNETCORE_URLS=http://+:$PORT
EXPOSE 8080

ENTRYPOINT ["dotnet", "perla_metro_stations_service_api.dll"]